// Mocks generated by Mockito 5.2.0 from annotations
// in ny_times/test/features/most_popular_articles/presentation/bloc/most_popular_articles_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ny_times/core/error/failures.dart' as _i6;
import 'package:ny_times/features/most_popular_articles/data/models/article.dart'
    as _i7;
import 'package:ny_times/features/most_popular_articles/domain/repository/most_popular_articls_repository.dart'
    as _i2;
import 'package:ny_times/features/most_popular_articles/domain/use_case/get_articles_use_case.dart'
    as _i4;
import 'package:ny_times/features/most_popular_articles/domain/use_case/param/param.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMostPopularArticlesRepo_0 extends _i1.Fake
    implements _i2.MostPopularArticlesRepo {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetArticleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetArticleUseCase extends _i1.Mock implements _i4.GetArticleUseCase {
  MockGetArticleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MostPopularArticlesRepo get articlesRepo =>
      (super.noSuchMethod(Invocation.getter(#articlesRepo),
              returnValue: _FakeMostPopularArticlesRepo_0())
          as _i2.MostPopularArticlesRepo);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ArticleModel>>> call(
          _i8.MostPopularParams? param) =>
      (super.noSuchMethod(Invocation.method(#call, [param]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i7.ArticleModel>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i7.ArticleModel>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ArticleModel>>>);
}
